# Generated by Django 2.1 on 2019-06-13 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='write_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 19, 10, 18, 883130)),
        ),
    ]
